[project]
name = "schooltools-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lukas Podobnik", email = "lukas.podobnik@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "textual>=8.2.8",
    "tomli-w>=1.2.0",
]

[project.scripts]
schooltools-tui = "schooltools_tui:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"
