id = "graphen"
curriculum_section_id = "INF12 4"
subject_id = "informatik-spaet-beginnend"
grade_level = 12
recommended_lesson_count = 10
titel = "Graphen"
stunden = [
    "stunde-01",
    "stunde-02",
    "stunde-03",
    "stunde-04",
    "stunde-05",
    "stunde-06",
    "stunde-07",
    "stunde-08",
    "stunde-09",
    "stunde-10",
]
