id = "informationssicherheit"
curriculum_section_id = "INF12 5"
subject_id = "informatik-spaet-beginnend"
grade_level = 12
recommended_lesson_count = 6
titel = "Informationssicherheit"
stunden = [
    "stunde-01",
    "stunde-02",
    "stunde-03",
    "stunde-04",
    "stunde-05",
    "stunde-06",
]
