id = "kommunikation-in-netzwerken-internet"
curriculum_section_id = "INF11 3"
subject_id = "informatik-ntg"
grade_level = 11
recommended_lesson_count = 10
titel = "Kommunikation in Netzwerken, Internet"
stunden = [
    "stunde-01",
    "stunde-02",
    "stunde-03",
    "stunde-04",
    "stunde-05",
    "stunde-06",
    "stunde-07",
    "stunde-08",
    "stunde-09",
    "stunde-10",
]
